swagger: '2.0'
info:
  version: 1.0.0
  title: CREST market prices API
host: crest-tq.eveonline.com
basePath: /market
schemes:
  - https
produces:
  - application/json
paths:
  /prices/:
    get:
      summary: Retrieve EVE market prices from CREST
      description: 'http://eveonline-third-party-documentation.readthedocs.io/en/latest/crest/eve/eve_market.html'
      operationId: requestMarketPrices
      tags:
        - Market Prices
      responses:
        200:
          description: Market price object
          schema:
            $ref: "#/definitions/MarketPrice"
definitions:
  MarketPrice:
    type: object
    properties:
      totalCount:
        type: number
        format: int32
      totalCount_str:
        type: string
      pageCount:
        type: number
        format: int32
      pageCount_str:
        type: string
      items:
        type: array
        items:
          type: object
          properties:
            adjustedPrice:
              type: number
              format: double
            averagePrice:
              type: number
              format: double
            'type':
              type: object
              properties:
                id_str:
                  type: string
                href:
                  type: string
                id:
                  type: number
                  format: int32
                name:
                  type: string
